steps:
  - name: 'gcr.io/cloud-builders/npm'
    args: ['ci']
  - name: 'gcr.io/cloud-builders/npm'
    args: ['run', 'export']
  - name: 'gcr.io/cloud-builders/gsutil'
    args: ['-m', 'cp', '-r', 'out/*', 'gs://sthlm.io']
  - name: 'gcr.io/cloud-builders/gsutil'
    args: ['rm', '-r', 'gs://sthlm.io/index']
  - name: 'gcr.io/cloud-builders/gsutil'
    args: ['-m', 'setmeta', '-h', 'Cache-Control:public, max-age=60, must-revalidate', 'gs://sthlm.io/*.html']
  - name: 'gcr.io/cloud-builders/gsutil'
    args: ['-m', 'setmeta', '-h', 'Cache-Control:public, max-age=60, must-revalidate', 'gs://sthlm.io/*/*.html']
  - name: 'gcr.io/cloud-builders/gsutil'
    args: ['-m', 'setmeta', '-h', 'Cache-Control:public, max-age=31536000, immutable', 'gs://sthlm.io/_next/**']
  - name: 'gcr.io/cloud-builders/gsutil'
    args: ['web', 'set', '-m', 'index.html', '-e', '404/index.html', 'gs://sthlm.io']
