steps:
  - name: 'gcr.io/cloud-builders/npm'
    args: ['ci']
  - name: 'gcr.io/cloud-builders/npm'
    args: ['run', 'export']
  - name: 'gcr.io/cloud-builders/gsutil'
    args: ['-m', 'cp', '-r', 'out/_next', 'gs://sthlm.io']
  - name: 'gcr.io/cloud-builders/gsutil'
    args: ['-m', 'cp', '-r', 'out/static', 'gs://sthlm.io']
  - name: 'gcr.io/cloud-builders/gsutil'
    args: ['-m', 'cp', 'out/404.html', 'gs://sthlm.io']
  - name: 'gcr.io/cloud-builders/gsutil'
    args: ['-m', 'cp', 'out/index.html', 'gs://sthlm.io']
  - name: 'gcr.io/cloud-builders/gsutil'
    args: ['-m', 'setmeta', '-h', 'Cache-Control:public, max-age=600, s-maxage=31536000', 'gs://sthlm.io/**']
  - name: 'gcr.io/cloud-builders/gsutil'
    args: ['web', 'set', '-m', 'index.html', '-e', '404.html', 'gs://sthlm.io']