name: ci

on:
  push:
    branches:
      - master
  pull_request:

jobs:
  web:
    if: ${{ github.event_name == 'push' }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push Docker image
        id: docker_build
        uses: docker/build-push-action@v5
        with:
          platforms: linux/amd64
          context: .
          file: ./Dockerfile
          push: true
          tags: |
            ghcr.io/sthlmio/web:1.0.${{ github.run_number }}
            ghcr.io/sthlmio/web:${{ github.sha }}
            ghcr.io/sthlmio/web:latest
